version: '3.9'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prd
    image: darpbr/laravel:prd
    container_name: laravel
    networks:
      - darpnet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prd
    image: darpbr/nginx:prd
    container_name: nginx
    networks:
      - darpnet
    ports:
      - "8080:80"

networks:
  darpnet:
    driver: bridge