name: ci-golang-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      with:
        go-version: '1.19.1'
      - run: go test